# Generated by Django 6.0.6 on 2026-06-10 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset (Debit Balance)"),
                            ("LIABILITY", "Liability (Credit Balance)"),
                            ("EQUITY", "Equity (Credit Balance)"),
                            ("REVENUE", "Revenue (Credit Balance)"),
                            ("EXPENSE", "Expense (Debit Balance)"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("description", models.TextField()),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.CreateModel(
            name="LedgerLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core_finance.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core_finance.journalentry",
                    ),
                ),
            ],
        ),
    ]
