# Generated by Django 6.0.6 on 2026-06-10 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerline",
            name="credit_base",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="ledgerline",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="ledgerline",
            name="debit_base",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="ledgerline",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("1.000000"), max_digits=12
            ),
        ),
    ]
