# Generated by Django 6.0.6 on 2026-06-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_finance", "0003_customer_invoice_invoiceline"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="receivable_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "ASSET"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core_finance.account",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core_finance.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="core_finance.invoice",
            ),
        ),
    ]
