"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Support env variables from .env file if defined
env_path = os.path.join(BASE_DIR, ".env")
if os.path.exists(env_path):
    load_dotenv(env_path)


# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-zq2mf5m2w%)=w!lqx+q(rk3x4vbxyc@6gi@gd!$9+3c*66c@ls",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (
    True
    if os.environ.get("DJANGO_DEBUG", "False").lower() in ("true", "1", "t")
    else False
)
# if not DEBUG:
#     SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or ""
#     if not SECRET_KEY or SECRET_KEY.startswith("django-insecure-"):
#         raise ValueError(
#             "CRITICAL SECURITY CONFIGURATION FAILURE: "
#             "A secure, production-grade DJANGO_SECRET_KEY must be provided in deployment."
#         )
# else:
#     # Use the local fallback insecure string when testing features locally
#     SECRET_KEY = os.environ.get(
#         "DJANGO_INSECURE_SECRET_KEY",
#         "django-insecure-zq2mf5m2w%)=w!lqx+q(rk3x4vbxyc@6gi@gd!$9+3c*66c@ls",
#     )

# 3. Dynamic Network Routing Boundaries
ALLOWED_HOSTS: list[str] = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host
]

# # Explicit flag allowing manual deactivation of SSL redirection loops locally
# SECURE_SSL_REQUIRED = os.environ.get("DJANGO_SECURE_SSL", str(not DEBUG)).lower() in (
#     "true",
#     "1",
#     "t",
#     "yes",
# )


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.iam.apps.IamConfig",
    "apps.core_finance.apps.CoreFinanceConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Enterprise Audit Engine Interceptor Registered Here
    "apps.iam.middleware.EnterpriseAuditMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Configure explicit root path directories for asset collation routines
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ASGI_APPLICATION = "config.asgi.application"


# Explicitly swap the primary authentication model to our RBAC/ABAC engine
AUTH_USER_MODEL = "apps_iam.EnterpriseUser"
# [SECURITY CONFIGURATION] Canonical location of the authentication gateway
LOGIN_URL = "apps_iam:login"

# [SECURITY CONFIGURATION] Default landing location upon successful authentication token initialization
LOGIN_REDIRECT_URL = "apps_iam:dashboard"

# [SECURITY CONFIGURATION] Forces all logout actions (App or Admin) to route directly back to the root page
LOGOUT_REDIRECT_URL = "/"

# # 3. Production Security Hardening Matrix Configuration
# if not DEBUG:
#     # Force HSTS policies (Enforces HTTPS on the client browser for 1 continuous year)
#     SECURE_HSTS_SECONDS = 31536000
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True

#     # Enforce cookie transit layer isolation flags
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True

#     # Prevent browsers from incorrectly inferring content types away from declared headers
#     SECURE_CONTENT_TYPE_NOSNIFF = True

#     # Activate cross-site scripting filter shields inside older browser runtimes
#     SECURE_BROWSER_XSS_FILTER = True
# else:
#     # Explicit development safeguards to ensure local tests run without SSL cert issues
#     SECURE_HSTS_SECONDS = 0
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False

# # 4. Dedicated SSL Routing Directive Rule block (Independent of DEBUG state)
# if SECURE_SSL_REQUIRED:
#     SECURE_SSL_REDIRECT = True
# else:
#     SECURE_SSL_REDIRECT = False
